# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gridstitcher',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/gridstitcher',
                'lib_path': 'gridstitcher'},
  'syms': {'gridstitcher.core': {'gridstitcher.core.foo': ('core.html#foo', 'gridstitcher/core.py')}}}
